name: Rust Clippy

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install system dependencies for Pango and GTK
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpango1.0-dev libgtk-4-dev

    - name: Install Clippy
      run: rustup component add clippy

    - name: Check
      run: cargo clippy -- -Dwarnings
